server:
  port: 8003
# mybatis配置
mybatis:
  type-aliases-package: com.atzelei.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# eureka的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8003  #修改eureka上的默认信息
    prefer-ip-address: true
#info配置
info:
  app.name: zelei-springcloud
  company.name: blog.zelei.com

