server:
  port: 3344
spring:
  application:
    name: springcloud-config-server-3344
    #链接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zelei641/springcloud-config.git
