server:
  port: 8764
spring:
  application:
    name: Eureka-Consumer
#Eureka配置
eureka:
  client:
    register-with-eureka: true #不向eureka中注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
# 开启降级
feign:
  hystrix:
    enabled: true

