server:
  port: 7003
#Eureka配置
eureka:
  instance:
    hostname: localhost3  #eureka服务端的实例名称
  client:
    fetch-registry: false #如果为false则表示自己为注册中心
    register-with-eureka: false #是否向eureka注册中心注册自己
    service-url: #eureka监控页面
      defaultZone: http://localhost1:7001/eureka/,http://localhost2:7002/eureka/
